def install_pathogen
  dir = File.expand_path "#{File.expand_path("../", __FILE__)}/autoload"
  FileUtils.mkdir_p(dir) unless File.exists?(dir)
  pdir = "#{dir}/vim-pathogen"
  install_plugin "tpope/vim-pathogen", "autoload"
  FileUtils.cp("#{pdir}/autoload/pathogen.vim", "#{dir}/pathogen.vim")
end

def install_plugin(repo, pluginDir = "bundle")
  name = File.basename(repo)
  cwd = File.expand_path("../", __FILE__)
  dir = File.expand_path("#{cwd}/#{pluginDir}/#{name}")

  namespace(name) do
    task :install do
      if(!File.exists?(dir))
        sh "git clone git://github.com/#{repo}.git \"#{dir}\""
      else
        Dir.chdir dir do
          sh "git pull"
        end
      end
    end
  end

  task name do

    puts
    puts "*" * 40
    puts "*#{"Installing #{name}".center(38)}*"
    puts "*" * 40
    puts
    Rake::Task["#{name}:install"].invoke
  end
  task :default => name
end


install_pathogen

install_plugin "scrooloose/nerdtree"
install_plugin "kien/ctrlp.vim"
install_plugin "mileszs/ack.vim"
install_plugin "ervandew/supertab"
install_plugin "OrangeT/vim-csharp"
install_plugin "Lokaltog/vim-easymotion"
install_plugin "garbas/vim-snipmate"

